FROM prefecthq/prefect:3.6.12-python3.11

RUN pip install --no-cache-dir \
    mlflow==3.11.1 \
    xgboost \
    scikit-learn \
    pandas \
    numpy \
    pyyaml \
    boto3 \
    requests \
    && pip cache purge
