FROM prefecthq/prefect:3.6.12-python3.11

RUN pip install --no-cache-dir \
    xgboost \
    scikit-learn \
    pandas \
    numpy \
    pyyaml \
    boto3 \
    requests \
    openpyxl \
    xlrd \
    dbt-postgres==1.9.* \
    && pip cache purge